# Generated by Django 4.1.5 on 2023-01-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='custom_attrs',
            field=models.JSONField(null=True),
        ),
    ]
